apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: codecritics/metrics-backend:latest
          imagePullPolicy: Always
          env:
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-tracing-agent.observability.svc.cluster.local
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /status
          readinessProbe:
            httpGet:
              port: 8080
              path: /status
      restartPolicy: Always