apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: codecritics/metrics-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /status
          readinessProbe:
            httpGet:
              port: 8080
              path: /status