apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: codecritics/metrics-trial:latest
          ports:
            - containerPort: 8080