apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: codecritics/metrics-trial:latest
          env:
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-tracing-agent.observability.svc.cluster.local
          ports:
            - containerPort: 8080