apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      release: prometheus
  endpoints:
    - port: trial
      path: /metrics
      interval: 20s
  namespaceSelector:
    matchNames:
      - default